# Generated by Django 3.0.5 on 2020-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='base',
            field=models.CharField(default='ERB', max_length=10),
        ),
    ]
