# Generated by Django 3.0.5 on 2020-04-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custodians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custodians.Custodian')),
            ],
        ),
    ]
