# Generated by Django 3.0.5 on 2020-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200412_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
