# Generated by Django 3.0.5 on 2020-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200412_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=8),
        ),
    ]
