# Generated by Django 3.0.5 on 2020-04-23 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('assets', '0005_auto_20200412_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='accessories',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='budgetCode',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='donor',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='physical_location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchaseDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchaseReference',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.SubCategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplierName',
            field=models.CharField(default='2', max_length=80),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
