# Generated by Django 3.0.5 on 2020-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposals', '0001_initial'),
        ('allocations', '0001_initial'),
        ('assets', '0006_auto_20200423_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allocation_ref',
            field=models.ManyToManyField(to='allocations.Allocation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_ref',
            field=models.ManyToManyField(to='disposals.Disposal'),
        ),
    ]
