# Generated by Django 3.0.5 on 2020-04-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200423_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='allocation_ref',
            new_name='allocations',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='disposal_ref',
            new_name='disposals',
        ),
    ]
