# Generated by Django 3.0.5 on 2020-04-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20200424_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='allocations',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disposals',
        ),
    ]
