# Generated by Django 3.0.5 on 2020-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposals', '0002_disposal_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposal',
            old_name='allocation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='disposal',
            old_name='document_number',
            new_name='documentNumber',
        ),
        migrations.AddField(
            model_name='disposal',
            name='base',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='disposal',
            name='comments',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='disposal',
            name='reason',
            field=models.CharField(default='', max_length=80),
        ),
    ]
