# Generated by Django 3.0.5 on 2020-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=40)),
                ('allocation_date', models.DateField()),
                ('previous_donor', models.CharField(max_length=25)),
                ('previous_budget', models.CharField(max_length=25)),
                ('new_donor', models.CharField(max_length=25)),
                ('new_program', models.CharField(max_length=25)),
                ('comments', models.CharField(max_length=140)),
            ],
        ),
    ]
